### PR TITLE
chore: project scaffold

### PR DESCRIPTION
**Pull request by raminjafary**

### CODE REVIEW

**Comment by farnabaz** [comment]
Thank you for your PR
I have somethings in my mind that affects project structure.

- We must create a simple way to import components separately, I personally like how `nextjs` do this. By creating components on the top level of the project anyone can import a single component like this `import Component from 'svelte-admin/component';`
- We can configure `storybook` in order to create an online demo instead of a public directory and example project.

@amiraliamhh

**Comment by amiraliamhh** [comment]
We don't need to compile this library (that should be handled by the project that is using this library), I think `storybook` would be enough and there is no need for webpack (or rollup, etc).

**Comment by raminjafary** [comment]
I just re-structured the project to support storybook and to build shareable svelte components. let me know if it meets the aforementioned criteria!

**Comment by raminjafary** [comment]
> We don't need to compile this library (that should be handled by the project that is using this library), I think `storybook` would be enough and there is no need for webpack (or rollup, etc).

It's true, but the purpose of this setup is to gain common consensus as it remains extendable as a standalone production.

**Pull request merged**
